### ISSUE TITLE
Totally new to github

### ISSUE THREAD

**Issue by Vivothrive** [jtmuller5/The-HustleGPT-Challenge#10]
I've started the challenge. Been working on it all day. 
I've started the #HustleGPT challenge.
My business has gone a bit over the budget but I got an apology from ChatGPT. 
VivoThrive is my business.

**Comment by jtmuller5** [comment]
Hi Vivothrive, do you have a Twitter account? 

In order to be added to the database I will need your product/business's name, a tagline, and a link if you have one.

Thanks!

**Comment by Vivothrive** [comment]
Hi Joe, Yes, my twitter handle is @London_lady and I have just created the business handle @VivoThriveMy business is in Health & Wellness and will be a affiliate marketing blog on health and wellness.Tagline: Empowering Your Wellness Journey The webpage is in work, www.vivothrive.com Thank you for this amazing information. I have been passionately working on it all day.Much appreciated. Lisa Pattenden  From: Joe MullerSent: 17 March 2023 20:02To: jtmuller5/The-HustleGPT-ChallengeCc: Vivothrive; AuthorSubject: Re: [jtmuller5/The-HustleGPT-Challenge] Totally new to github (Issue #10) Hi Vivothrive, do you have a Twitter account?In order to be added to the database I will need your product/business's name, a tagline, and a link if you have one.Thanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by jtmuller5** [comment]
Added!
