### ISSUE TITLE
Co-creating an indie game together with GPT-4

### ISSUE THREAD

**Issue by rafalkorbaczynski** [jtmuller5/The-HustleGPT-Challenge#19]
Hey! I'm co-creating an indie game with GPT-4 in a week using a modified version of the HustleGPT prompt. We (me and ChatGPT) are planning to sell the game on Steam at the end of the week. 
Would you mind adding me to the list?
Product name: AI Unbound
Tagline: A game crafted by both human and artificial minds.
Link: https://twitter.com/dreamulatorgame/status/1637436858920566784?s=20

Here's my modified version of the HustleGPT prompt:
![1st prompt](https://user-images.githubusercontent.com/128299403/226177095-d2ec5b41-4bc8-4b15-9121-cf13aac55303.png)

**Comment by jtmuller5** [comment]
Added!
